
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS pantries CASCADE;
DROP TABLE IF EXISTS allergies CASCADE;
DROP TABLE IF EXISTS saved_recipes CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE pantries (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  expirations DATE
);

CREATE TABLE allergies (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE saved_recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  recipe_id INTEGER NOT NULL,
  created_at DATE 
);

ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE pantries_id_seq RESTART WITH 1;
ALTER SEQUENCE allergies_id_seq RESTART WITH 1;
ALTER SEQUENCE saved_recipes_id_seq RESTART WITH 1;
